In [0]:
import torch

In [0]:
x = torch.ones([3, 3])

In [0]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
x = torch.rand([3, 3])
x

tensor([[0.8690, 0.5377, 0.7260],
        [0.8965, 0.2177, 0.5220],
        [0.6133, 0.2409, 0.1219]])

In [0]:
#копирование
y = x.clone()


In [0]:
#логические маски
y = y[y > 0.5]
y

tensor([0.8690, 0.5377, 0.7260, 0.8965, 0.5220, 0.6133])

In [0]:
y.shape

torch.Size([6])

In [0]:
#Конвертация из numpy массива в torch и обратно
import numpy
a = numpy.ones([3, 3])

b = torch.from_numpy(a)
print(type(a), type(b))

c = b.numpy()
print(type(b), type(c))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [0]:
#доступность вычислений на GPU
torch.cuda.is_available()

True

In [0]:
#Смена устройства для вычислений
torch.device('cuda:0')
#torch.device('cpu')

device(type='cuda', index=0)

In [0]:
#Закрепление вычислительного устройства за тензором
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
x_cuda = x.to(device)

In [0]:
#Демонстрация ускорения
x_test = torch.rand([3000, 3000])
x_test_cuda = x_test.to(device)
x_test_not_cuda = x_test.to('cpu')

%time
y_cuda = (x_test_cuda - x_test_cuda + x_test_cuda * 10.0)**2

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 6.44 µs


In [0]:
%time
y_not_cuda = (x_test_not_cuda - x_test_not_cuda + x_test_not_cuda * 10.0)**2

CPU times: user 11 µs, sys: 4 µs, total: 15 µs
Wall time: 19.1 µs
